#!/bin/bash
# Copyright (c) 2025-present WATonomous. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

# This script generates a .env file to be used with docker-compose
# To override any of the variables in this script, create watod-config.sh
#   in the same directory and populate it with variables
#   e.g. `COMPOSE_PROJECT_NAME=<NAME>`.

if [ -f /.dockerenv ]; then
	echo "Please run this in the host machine (not in the Docker container)"
	exit 1
fi

# Retrieve git branch
if ! [ -x "$(command -v git)" ]; then
    echo 'Error: git is not installed.' >&2
else
    BRANCH=${BRANCH:-$(git branch --show-current)}
fi

## ----------------------- Configuration (Subject to Override) ----------------------------

COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-watod_$USER}

# Tag to use. Images as formatted as <IMAGE_NAME>:<TARGET_STAGE>-<TAG> with forward slashes replaced
# with dashes
TAG=$(echo "${TAG:-$BRANCH}" | tr / -)
# replace / with -
TAG=${TAG/\//-}

# List of active profiles to run, defined in docker-compose.yaml.
# Possible values:
#   - vis_tools     		  :   starts visualization tools (vnc and foxglove)
#   - production    		  :   configs for all containers required in production
#   - samples             :   starts sample ROS2 pubsub nodes
ACTIVE_MODULES=${ACTIVE_MODULES:-""}

# Docker Registry to pull/push images
REGISTRY_URL=${REGISTRY_URL:-"ghcr.io/watonomous/wato_asd_training"}

## --------------------------- Images -------------------------------
# NOTE: ALL IMAGE NAMES MUCH BE IN THE FORMAT OF <COMPOSE_FILE>_<SERVICE>

# ROS2 C++ Samples
SAMPLES_AGGREGATOR_IMAGE=${SAMPLES_AGGREGATOR_IMAGE:-"$REGISTRY_URL/samples_aggregator"}
SAMPLES_PRODUCER_IMAGE=${SAMPLES_PRODUCER_IMAGE:-"$REGISTRY_URL/samples_producer"}
SAMPLES_TRANSFORMER_IMAGE=${SAMPLES_TRANSFORMER_IMAGE:-"$REGISTRY_URL/samples_transformer"}

# ASD Training Images
GAZEBO_SERVER_IMAGE=${GAZEBO_SERVER_IMAGE:-"$REGISTRY_URL/gazebo_server"}
INFRASTRUCTURE_FOXGLOVE_IMAGE=${INFRASTRUCTURE_FOXGLOVE_IMAGE:-"$REGISTRY_URL/infrastructure_foxglove"}
ROBOT_IMAGE=${ROBOT_IMAGE:-"$REGISTRY_URL/robot"}

## -------------------- Multi-Machine ROS2 Config -------------------

ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

## --------------------------- Ports ------------------------------

BASE_PORT=${BASE_PORT:-$(($(id -u)*20))}
FOXGLOVE_BRIDGE_PORT=${FOXGLOVE_BRIDGE_PORT:-$((BASE_PORT++))}
GAZEBO_PORT=${GAZEBO_PORT:-$((BASE_PORT++))}

## -------------------- Environment Variables -------------------------

# General
echo "$MODULES_DIR"
{
    echo "# Auto-generated by ${BASH_SOURCE[0]}. Edit at own risk."
    echo "MODULES_DIR=$MODULES_DIR"
    echo "MONO_DIR=$MONO_DIR"
    echo "ACTIVE_MODULES=\"$ACTIVE_MODULES\""
    echo "COMPOSE_DOCKER_CLI_BUILD=1"
    echo "COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME"
    echo "TAG=$TAG"
    echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID"
    echo "BASE_PORT=$BASE_PORT"
    echo "FOXGLOVE_BRIDGE_PORT=$FOXGLOVE_BRIDGE_PORT"
    echo "GAZEBO_PORT=$GAZEBO_PORT"
    echo "SAMPLES_AGGREGATOR_IMAGE=$SAMPLES_AGGREGATOR_IMAGE"
    echo "SAMPLES_PRODUCER_IMAGE=$SAMPLES_PRODUCER_IMAGE"
    echo "SAMPLES_TRANSFORMER_IMAGE=$SAMPLES_TRANSFORMER_IMAGE"
    echo "GAZEBO_SERVER_IMAGE=$GAZEBO_SERVER_IMAGE"
    echo "INFRASTRUCTURE_FOXGLOVE_IMAGE=$INFRASTRUCTURE_FOXGLOVE_IMAGE"
    echo "ROBOT_IMAGE=$ROBOT_IMAGE"
} > "$MODULES_DIR/.env"
