#!/bin/bash
# Copyright (c) 2025-present WATonomous. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -e

programname="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
MONO_DIR="$(dirname "$(realpath "$0")")"
MODULES_DIR="$MONO_DIR/modules"

function usage {
    echo "Usage: $programname [OPTIONS]... [COMMAND]..."
    echo "Executes \"docker compose COMMAND\" in the the monorepo with appropriate environment variables."
    echo "  -v --verbose                    verbose mode. Currently, prints .env variables"
    echo "  -t --terminal [service_name]    open a bash terminal into the desired service (eg: perception)."
    echo ""
    echo "Examples:"
    echo "  watod up                       start containers (docker compose up)"
    echo "  watod down                     stop and remove containers (docker compose down)"
    echo "  watod ps [--services]          list containers in the current project and show their current status (docker compose ps)"
    echo "  watod -t perception            open a bash terminal into the perception container."
    echo ""
    echo " More Info on Docker Compose: https://docs.docker.com/compose/reference/overview/"
    exit 0
}

function run_compose {
    cd "$MONO_DIR"
    if [ -n "$(source "$MODULES_DIR"/.env && echo "$ACTIVE_MODULES")" ] && [ -z "$MODULES" ]; then
        # Read ACTIVE_MODULES as a space-separated string
        local modules_str
        modules_str="$(source "$MODULES_DIR"/.env && echo "$ACTIVE_MODULES")"
        MODULES=""
        for module in $modules_str; do
            MODULES="$MODULES -f $MODULES_DIR/docker-compose.${module}.yaml"
        done
    fi

    echo "Running docker compose --profile ${MODE_OF_OPERATION}${MODULES} $*"
    # shellcheck disable=SC2086
    DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1} docker compose --profile "${MODE_OF_OPERATION}" ${MODULES} "$@"
}

# in case you need help
if [ "$1" = 'help' ]; then
    usage
fi

# in case you have nothing to say
if [ $# = 0 ]; then
    usage
fi

# run options
COMPOSE_CMD=""
while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
      -v|--verbose)
        VERBOSE=1
        shift # past argument
        ;;
      -d|--setup-dev-env)
        SETUP_DEV_ENVIRONMENT=1
        shift
        SERVICE_NAME=$1
        if [ -z "$SERVICE_NAME" ]; then
            echo "Expected watod -d SERVICE_NAME"
            usage
        fi
        shift
        ;;
      -c|--setup-completion)
        SETUP_COMPLETION=1
        shift
        ;;
      -t|--terminal)
        START_TERMINAL=1
        shift
        SERVICE_NAME=$1
        if [ -z "$SERVICE_NAME" ]; then
            echo "Expected watod -t SERVICE_NAME"
            usage
        fi
        shift
        ;;
      -h|--help) # in case you got this far, but still need help :)
        usage
        ;;
      *) # unknown option
        break
        ;;
    esac
done

if [[ $# -gt 0 ]]; then
	COMPOSE_CMD="${COMPOSE_CMD} $*"
fi

# Allow for local overrides of any of the below parameters (prioritized your local config)
if [ -f "$MONO_DIR/watod-config.local.sh" ]; then
	source "$MONO_DIR/watod-config.local.sh"
elif [ -f "$MONO_DIR/watod-config.sh" ]; then
	source "$MONO_DIR/watod-config.sh"
fi

MODE_OF_OPERATION=${MODE_OF_OPERATION:-"deploy"}
PLATFORM=${PLATFORM:-"amd64"}

# generate .env file from watod_scripts/watod-setup-docker-env.sh
if [ -n "$VERBOSE" ]; then # if we want to see all verbose coming from setting up env
    cd "$MONO_DIR" && . ./watod_scripts/watod-setup-docker-env.sh
else
    cd "$MONO_DIR" && . ./watod_scripts/watod-setup-docker-env.sh &> /dev/null
fi

# override to use arm64 images
if [ "$PLATFORM" = "arm64" ]; then
    echo "BASE_IMAGE_OVERRIDE=ghcr.io/watonomous/rover/base:humble-arm64" >> "$MODULES_DIR/.env"
else
    echo "BASE_IMAGE_OVERRIDE=ghcr.io/watonomous/robot_base/base:humble-ubuntu22.04" >> "$MODULES_DIR/.env"
fi

if [ -n "$SETUP_COMPLETION" ]; then
    source ./watod_scripts/watod-completion.bash
fi

# custom docker compose command to setup development environments outside containers
if [ -n "$SETUP_DEV_ENVIRONMENT" ]; then
    source ./watod_scripts/watod-setup-dev-env.sh "$SERVICE_NAME"
    exit
fi

if [ -n "$COMPOSE_CMD" ]; then
    ADDITIONAL_ARGS=""
    # If we are starting a terminal, run docker compose up with the -d argument
    if [ -n "$START_TERMINAL" ] && [[ ! " $COMPOSE_CMD " =~ " -d " ]] && [[ " $COMPOSE_CMD " =~ " up " ]]; then
        ADDITIONAL_ARGS="-d"
    fi
    # shellcheck disable=SC2086
    run_compose $COMPOSE_CMD ${ADDITIONAL_ARGS}
fi

if [ -n "$START_TERMINAL" ]; then
    echo "Starting bash shell in service $SERVICE_NAME":
    run_compose exec "$SERVICE_NAME" /bin/bash
fi
